name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go run build/build.go ${{ github.ref_name }}

      - name: Archive
        run: |
          cd release
          for file in *; do
            zip "${file}.zip" "$file"
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.zip
